# This pipeline builds a Docker image.
# It does not push it to a registry yet.

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'Build a Docker image'
  inputs:
    command: 'build'
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: |
      latest